### ISSUE TITLE
Posts belong in ./src?

### ISSUE THREAD

**Issue by jacobpdq** [infiniteluke/next-static#12]
I'm wondering if .mds of posts should belong in ./src/posts.

If I also wanted to source markdown into a page and generate the page in the same manner, I wouldn't want to clutter up the pages directory with a .md file corresponding to the page. I'd rather put it in the ./src/pages directory, then pull the content in.

Thoughts?

**Comment by infiniteluke** [comment]
Hi @jacobpdq! Thanks for checking out the project 😄 

New posts belong in the `posts` directory. `src` is reserved for source code and shouldn't need to be touched unless you feel like hacking things up. 

Please see the readme for how to add new posts:
https://github.com/infiniteluke/next-static#writting

**Comment by jacobpdq** [comment]
Hey, thanks for the tip.

Instead of ```src``` I've stashed my source content in ```static/assets/copy``` under either ```pages``` or ```posts```. My intention is to abstract the source to handle page & post markdown injection..

**Comment by infiniteluke** [comment]
Sounds cool! Do submit a PR if you think it's general enough to contribute. Thanks for checking out the project. 👍
