### ISSUE TITLE
Calling all posts

### ISSUE THREAD

**Issue by jacobpdq** [infiniteluke/next-static#13]
imo https://github.com/tscanlin/next-blog/blob/master/pages/post.js has a much cleaner method of calling posts (see ```Index(props)```) – a query/require match makes more sense rather than loading all posts in. Thoughts?

**Comment by infiniteluke** [comment]
Hi - I don't agree that it is cleaner. I avoid dynamic requires whenever possible. They're DRY but hard to grep for. I think the method for getting posts could be changed into a paging strategy to avoid loading _all_ posts. Paging is a much cleaner solution in my opinion. 

Please leave comments on #3 with your thoughts! PRs are always welcome!

**Comment by infiniteluke** [comment]
Hi - I don't agree that it is cleaner and I avoid dynamic requires whenever possible. 

That said, you're right, we shouldn't be pulling in _all_ posts. For next-static, I would prefer a paging strategy. Paging is a much cleaner solution in my opinion. 

Please leave comments on #3 with your thoughts! PRs are always welcome!

**Comment by jacobpdq** [comment]
Any reason why you avoid dynamic requires? Is this a fringe case?

J

**Comment by infiniteluke** [comment]
No, there are plenty of times when dynamic requires are fine, but they're often overly DRY. I find them most useful for factory/plugin patterns.
