### ISSUE TITLE
Reason for switch to nodemon vs babel preval

### ISSUE THREAD

**Issue by sammdec** [infiniteluke/next-static#8]
Hi there, thanks for creating this I wanted to create the exact same thing for my blog so this has been really handy to learn from. 

I had one question though and that was why you switched from using the babel preval plugin to using the nodemon method you seem to be using now? Did you find one faster or easier to maintain?

**Comment by infiniteluke** [comment]
Thanks @samjbmason! In short, babels cache was causing changes to markdown files not to be picked up. Read this issue for an overview: https://github.com/kentcdodds/babel-plugin-preval/issues/19

Also, PRs are welcome and encouraged!

**Comment by infiniteluke** [comment]
Thanks @samjbmason! In short, babels cache was causing changes to markdown files not to be picked up. Read this issue for an overview: kentcdodds/babel-plugin-preval#19

Also, PRs are welcome and encouraged!
